import json
import urllib.request
import urllib.error
from typing import Optional
from .question_generation import QuizQuestion, QuestionType

LLM_PROMPT = """You are an advanced NLP-based quiz generation engine.
Your task is to generate clear, accurate, and student-friendly questions from the given extracted PDF text.

INPUT TEXT:
{text}

INSTRUCTIONS:
1. Carefully understand the content before generating questions.
2. Generate three types of questions ONLY:
   - Multiple Choice Questions (MCQs)
   - Fill in the Blanks
   - True/False

3. General Rules:
   - Questions must be clear, concise, and unambiguous
   - Do NOT copy sentences directly — rephrase intelligently
   - Ensure questions are based strictly on the input text
   - Avoid vague or subjective questions
   - Keep language simple and easy to understand

4. MCQ Rules:
   - Provide exactly 4 options
   - Only ONE correct answer
   - Distractors should be plausible (not obvious wrong answers)

5. Fill in the Blanks Rules:
   - Remove a key term from a sentence
   - Use "_____" to represent the blank
   - Ensure the sentence still gives enough context

6. True/False Rules:
   - Statements must be fact-based
   - Avoid tricky or misleading wording

7. Difficulty Levels:
   - Easy -> direct facts
   - Medium -> understanding concepts
   - Hard -> inference or application

OUTPUT FORMAT (STRICT JSON):
[
  {{
    "question": "...",
    "type": "MCQ",
    "difficulty": "Easy",
    "options": ["A", "B", "C", "D"],
    "answer": "...",
    "explanation": "..."
  }},
  {{
    "question": "...",
    "type": "FillBlank",
    "difficulty": "Medium",
    "answer": "...",
    "explanation": "..."
  }}
]

IMPORTANT:
- Do NOT include options for FillBlank or TrueFalse
- Ensure answer accuracy
- Explanation must clearly justify the answer in 1-2 lines
- Return ONLY the raw valid JSON array, do not start with ```json or any other text.
"""

def call_ollama(text: str, model: str = "llama3") -> Optional[list[QuizQuestion]]:
    url = "http://localhost:11434/api/generate"
    # Take a chunk of text to prevent exceeding context window for local LLMs
    payload = {
        "model": model,
        "prompt": LLM_PROMPT.format(text=text[:3000]),
        "stream": False,
        "format": "json"
    }
    
    try:
        req = urllib.request.Request(url, data=json.dumps(payload).encode('utf-8'), headers={'Content-Type': 'application/json'})
        response = urllib.request.urlopen(req, timeout=90)
        result = json.loads(response.read().decode('utf-8'))
        
        # Try to parse the JSON array generated by the LLM
        generated_data = json.loads(result["response"])
        
        quiz_questions = []
        for i, q in enumerate(generated_data):
            q_type = q.get("type", "").lower()
            mapped_type = QuestionType.MCQ.value
            if "fill" in q_type:
                mapped_type = QuestionType.FILL_BLANK.value
            elif "true" in q_type:
                mapped_type = QuestionType.TRUE_FALSE.value
            
            # Map True/False text answer to actual boolean for frontend compatibility
            ans = q.get("answer", "")
            if mapped_type == QuestionType.TRUE_FALSE.value:
                ans = str(ans).strip().lower() in ["true", "t", "yes", "1"]
                
            quiz_questions.append(QuizQuestion(
                id=f"llm-{i}",
                type=mapped_type,
                prompt=f"[{q.get('difficulty', 'Medium')}] {q.get('question', '')}",
                answer=ans,
                options=q.get("options", []),
                source_sentence="Generated intelligently by Local LLM.",
                explanation=q.get("explanation", ""),
            ))
            
        return quiz_questions if quiz_questions else None
        
    except Exception as e:
        print(f"Local LLM Generation Failed (Requires Ollama running locally): {e}")
        return None
